###
# File: .drone.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Thursday, September 17th 2020, 7:16:54 pm
# Last Modified: Monday, November 21st 2022, 4:52:59 pm
#
# http://www.opensource.org/licenses/MIT
###

kind: pipeline
name: default
type: docker

steps:
  - name: "test and build"
    image: golang:1.19
    environment:
      GOPROXY: "https://goproxy.cn,direct"
    commands:
      - make

  - name: "push docker image to huawei cloud"
    image: plugins/docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      GOPROXY: "https://goproxy.cn,direct"
    when:
      branch:
        - master
      event:
        - push
    settings:
      registry: swr.cn-east-2.myhuaweicloud.com
      repo: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns
      username:
        from_secret: huawei_docker_username
      password:
        from_secret: huawei_docker_password
      build_args_from_env:
        - GITEA_TOKEN
      dockerfile: Dockerfile
      tags:
        - latest
        - 1.4.4

  - name: "push docker image to github"
    image: plugins/docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      GOPROXY: "https://goproxy.cn,direct"
    when:
      branch:
        - master
      event:
        - push
    settings:
      registry: ghcr.io
      repo: ghcr.io/mingcheng/simplyddns
      username:
        from_secret: ghcr_docker_username
      password:
        from_secret: ghcr_docker_password
      dockerfile: Dockerfile
      tags:
        - latest
        - 1.4.4

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
