###
# File: .drone.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Thursday, September 17th 2020, 7:16:54 pm
# Last Modified: Wednesday, January 6th 2021, 8:44:53 pm
#
# http://www.opensource.org/licenses/MIT
###

kind: pipeline
name: default
type: docker

steps:
  - name: test-and-build
    image: golang:1.15
    environment:
      GOPROXY: "https://goproxy.cn,direct"
    commands:
      - make test build

  - name: publish-docker-image
    image: plugins/docker
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
      GOPROXY: "https://goproxy.cn,direct"
    when:
      branch: master
      event: push
    settings:
      registry: swr.cn-east-2.myhuaweicloud.com
      repo: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - GITEA_TOKEN
      dockerfile: Dockerfile
      custom_dns: 119.29.29.29
      mirror: https://pqbap4ya.mirror.aliyuncs.com/
      tags:
        - latest
