###
# File: .drone.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Thursday, September 17th 2020, 7:16:54 pm
# Last Modified: Monday, July 12th 2021, 3:09:29 pm
#
# http://www.opensource.org/licenses/MIT
###

kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.16
    environment:
      GOPROXY: "https://goproxy.cn,direct"
      GITEA_TOKEN:
        from_secret: gitea_token
      NSQ_ADDR: "192.168.1.200:4150"
    commands:
      - env
      - git config --global url."https://$GITEA_TOKEN@repo.wooramel.cn/".insteadOf "https://repo.wooramel.cn/"
      - make test

  - name: publish-image
    image: plugins/docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
      GOPROXY: "https://goproxy.cn,direct"
    when:
      branch:
        - master
      event:
        - push
    settings:
      registry: swr.cn-east-2.myhuaweicloud.com
      repo: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - GITEA_TOKEN
      dockerfile: Dockerfile
      custom_dns: 119.29.29.29
      mirror: https://pqbap4ya.mirror.aliyuncs.com/
      tags:
        - latest
        - 1.3.0

  - name: publish-arm64-image
    image: thegeeklab/drone-docker-buildx
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    when:
      branch:
        - master
      event:
        - push
    settings:
      registry: quay.io
      privileged: true
      repo: quay.io/mingcheng/simplyddns
      platforms: linux/arm64/v8
      username:
        from_secret: quay_io_username
      password:
        from_secret: quay_io_password
      build_args_from_env:
        - GITEA_TOKEN
      dockerfile: Dockerfile.arm64
      tags:
        - latest
        - 1.3.0

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
