version: "3"

services:
  simplyddns:
    build:
      context: .
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./example/basic.yml:/simplyddns.yml:ro
