version: "3"

services:
  simplyddns:
    build:
      context: .
      args:
        GITEA_TOKEN: ${GITEA_TOKEN}
    #    image: ghcr.io/mingcheng/simplyddns:1.2.1
    image: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:1.3.1
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./example/basic.yml:/simplyddns.yml:ro
