version: "3"

services:
  simplyddns:
    build:
      context: .
      args:
        GITEA_TOKEN: ${GITEA_TOKEN}
    image: ghcr.io/mingcheng/simplyddns
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./example/basic.yml:/simplyddns.yml:ro
