version: "3"
services:
  simplyddns:
    build:
      context: .
      args:
        GITEA_TOKEN: $GITEA_TOKEN
    image: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:1.2.0
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./example/basic.yml:/simplyddns.yml:ro
