version: "3"

services:
  simplyddns:
    build:
      context: .
    image: ghcr.io/mingcheng/simplyddns:1.4.2
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./example/basic.yml:/simplyddns.yml:ro
