apiVersion: v1
kind: ConfigMap
metadata:
  name: simplyddns-config
data:
  simplyddns.yml: |-
    logfile: "/dev/stderr"
    debug: Yes

    ddns:
      - source:
          type: "lo"
          interval: 60 # 1 minute
        target:
          type: "sleep"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplyddns-deployment
spec:
  selector:
    matchLabels:
      app: simplyddns
  replicas: 1
  template:
    metadata:
      labels:
        app: simplyddns
    spec:
      containers:
        - name: simplyddns
          image: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Shanghai"
          volumeMounts:
            - name: config
              mountPath: /simplyddns.yml
              subPath: simplyddns.yml
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: simplyddns-config
