###
# File: k8s-deploy.yml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Wednesday, January 6th 2021, 8:46:46 pm
# Last Modified: Thursday, January 7th 2021, 8:19:31 pm
#
# http://www.opensource.org/licenses/MIT
###

apiVersion: v1
kind: ConfigMap
metadata:
  name: simplyddns-config
data:
  simplyddns.yml: |-
    logfile: "/dev/stderr"
    debug: Yes
    ddns:
      - source:
          type: "lo"
          interval: 60 # 1 minute
        target:
          type: "sleep"
---
apiVersion: v1
kind: Pod
metadata:
  name: simplyddns
  labels:
    app: simplyddns
spec:
  containers:
    - name: simplyddns
      image: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "Asia/Shanghai"
      volumeMounts:
        - name: config
          mountPath: /simplyddns.yml
          subPath: simplyddns.yml
          readOnly: true
  restartPolicy: Always
  volumes:
    - name: config
      configMap:
        name: simplyddns-config
