version: '3'

vars:
  BINARY_NAME: simplyddns{{exeExt}}
  PACKAGE_NAME: github.com/mingcheng/socks5lb
  VERSION: '1.5.0'

tasks:
  default:
    deps:
      - test
      - build

  build:
    deps:
      - clean
    sources:
      - ./cmd/simplyddns/*.go
      - ./source/*.go
      - ./target/*.go
      - ./*.go
    generates:
      - '{{.BINARY_NAME}}'
    cmds:
      - >
        go build -o {{.BINARY_NAME}} -ldflags="
        -X 'main.BuildCommit={{.GIT_COMMIT}}'
        -X 'main.BuildTime={{now | date "2006-01-02"}}'
        -X 'main.BuildVersion={{.VERSION}}'"
        ./cmd/simplyddns
    vars:
      GIT_COMMIT:
        sh: git rev-parse --short HEAD
    silent: true

  test:
    deps:
      - clean
    cmds:
      - go test -v ./...

  clean:
    aliases:
      - cleanup
      - clear
    cmds:
      - go clean ./...
    silent: true
