#!#
# Copyright (c) 2025 Hangzhou Guanwaii Technology Co,.Ltd.
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: build.yaml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-02-28 10:52:26
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-03-12 13:44:31
##

name: build

on:
  push:
    branches:
      - develop

env:
  GOPRIVATE: ".github.com,git.guanwaii.com"
  GOPROXY: "https://goproxy.cn,direct"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        go-version: ["1.22", "1.23", "1.24"]
=======
        go-version: [ "1.20", "1.21", "1.22" ]
>>>>>>> da5b87a (update the test items)

    steps:
      - uses: actions/checkout@v4
      - name: set go with version ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
<<<<<<< HEAD
      - run: |
          env
          id
          uname -a
          go version
          go env
          make build
=======
      - run: go env
      - run: make build
>>>>>>> da5b87a (update the test items)
