#name: schedule
---
on:
  schedule:
    - cron: '*/1 * * * *'
#  push:
#    branches:
#      - 'develop'
jobs:
  check:
    runs-on: ubuntu-latest
    #    container: catthehacker/ubuntu:act-latest
    steps:
      - run: echo "Hello, World!"
