#!#
# Copyright (c) 2024-2025 Hangzhou Guanwaii Technology Co,.Ltd.
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: tcr.yaml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2024-11-15 14:46:48
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-02-28 10:57:18
##

name: build an image and push it to registry

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - id: commit
      #   uses: prompt/actions-commit-hash@v3
      # - id: meta
      #   uses: docker/metadata-action@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.12.4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}
          registry: ccr.ccs.tencentyun.com
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ccr.ccs.tencentyun.com/mingcheng/simpleddns:latest
            ccr.ccs.tencentyun.com/mingcheng/simpleddns:${{ steps.commit.outputs.short }}
