###
# File: tcr.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, December 26th 2023, 9:18:36 pm
# Last Modified: Wednesday, December 27th 2023, 9:18:19 am
#
# https://opensource.org/licenses/MIT
###

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker Image To Tencentyun and HuaweiCloud

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - id: meta
        uses: docker/metadata-action@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.12.4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}
          registry: ccr.ccs.tencentyun.com
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: swr.cn-east-2.myhuaweicloud.com

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ccr.ccs.tencentyun.com/mingcheng/simpleddns:latest
            ccr.ccs.tencentyun.com/mingcheng/simpleddns:${{ steps.commit.outputs.short }}
            swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:latest
            swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:${{ steps.commit.outputs.short }}
