###
# File: tcr.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, December 26th 2023, 9:18:36 pm
# Last Modified: Wednesday, December 27th 2023, 9:32:30 am
#
# https://opensource.org/licenses/MIT
###

name: build an image and push it to registry

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - id: meta
        uses: docker/metadata-action@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.12.4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}
          registry: ccr.ccs.tencentyun.com
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ccr.ccs.tencentyun.com/mingcheng/simpleddns:latest
            ccr.ccs.tencentyun.com/mingcheng/simpleddns:${{ steps.commit.outputs.short }}
