###
# File: test.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Wednesday, December 27th 2023, 9:33:00 am
# Last Modified: Wednesday, December 27th 2023, 9:38:20 am
#
# https://opensource.org/licenses/MIT
###

name: test golang external proxies

on:
  schedule:
    - cron: '5 2 * * 1,3,5'
#  push:
#    branches:
#      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - run: go env
      - run: make test
