###
# File: test.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, December 26th 2023, 9:40:59 pm
# Last Modified: Tuesday, December 26th 2023, 10:28:53 pm
#
# https://opensource.org/licenses/MIT
###

name: ci

on:
  push:
    branches:
      - "develop"

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     buildkitd-flags: --debug

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     registry: swr.cn-east-2.myhuaweicloud.com

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     # context: .
      #     # platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:20231226

      - name: Login to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          region: cn-east-2
          access-key-id: "HL5AS0J3YSCKFIIISZST"
          access-key-secret: "fZXwIcc5txpaXMpBIR2fmXzFEMIUflmp3h3LGBdt"

      - name: Build Docker image for multiplatform
        uses: huaweicloud/swr-multiplatform-build-action@v1.2.0
        with:
          image_tag: swr.cn-east-2.myhuaweicloud.com/mingcheng/simplyddns:20231226
          platforms: linux/amd64,linux/arm64
          use_latest_buildx: false
          push: true
          file: ./Dockerfile
