###
# File: test.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, December 26th 2023, 9:40:59 pm
# Last Modified: Tuesday, December 26th 2023, 9:47:46 pm
#
# https://opensource.org/licenses/MIT
###

name: ci

on:
  push:
    branches:
      - "develop"

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: swr.cn-east-2.myhuaweicloud.com

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: mingcheng/simplyddns:latest
