###
# File: test.yaml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-02-28 10:52:26
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-03-12 13:42:53
##

name: test golang external proxies

on:
  schedule:
    - cron: '30 2 * * *'
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - run: go env
      - run: make test
